CONTAINER opyedgetosplineobject
{
	NAME opyedgetosplineobject;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		LINK ID_EDGETOSPLINE_INPUTLINK {}
		STRING ID_EDGETOSPLINE_EDGESELECTION {}
		BOOL ID_EDGETOSPLINE_OVERRIDETYPE {}
		LONG ID_EDGETOSPLINE_SPLINETYPE
		{
			CYCLE
			{
				ID_EDGETOSPLINE_LINEAR;
				ID_EDGETOSPLINE_AKIMA;
				ID_EDGETOSPLINE_BSPLINE;
			}
		}
		LONG ID_EDGETOSPLINE_SUBDIVISIONS { MIN 0; }
	}
}
