#ifndef OPYEDGETOSPLINE_H_
#define OPYEDGETOSPLINE_H_

enum
{
	ID_EDGETOSPLINE_EDGESELECTION = 1000,
	ID_EDGETOSPLINE_INPUTLINK = 1001,
	ID_EDGETOSPLINE_SPLINETYPE = 1002,
	ID_EDGETOSPLINE_LINEAR = 0,
	ID_EDGETOSPLINE_AKIMA = 1,
	ID_EDGETOSPLINE_BSPLINE = 2,
	ID_EDGETOSPLINE_SUBDIVISIONS = 1003,
	ID_EDGETOSPLINE_OVERRIDETYPE = 1004
};

#endif // OPYEDGETOSPLINE_H_